In [ ]:

import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/netflix_movies_data.csv")

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df.shape

(8807, 12)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
df = df.replace(np.nan, ' ')

In [ ]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,,,,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df['tags'] = df['listed_in'] + df['description']

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,tags
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",DocumentariesAs her father nears the end of hi...
1,s2,TV Show,Blood & Water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...","International TV Shows, TV Dramas, TV Mysterie..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,,,,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...","Docuseries, Reality TVFeuds, flirtations and t..."
4,s5,TV Show,Kota Factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,"International TV Shows, Romantic TV Shows, TV ..."

In [ ]:
new_df = df[['title', 'type','tags']]

In [ ]:
new_df

,title,type,tags
0,Dick Johnson Is Dead,Movie,DocumentariesAs her father nears the end of hi...
1,Blood & Water,TV Show,"International TV Shows, TV Dramas, TV Mysterie..."
2,Ganglands,TV Show,"Crime TV Shows, International TV Shows, TV Act..."
3,Jailbirds New Orleans,TV Show,"Docuseries, Reality TVFeuds, flirtations and t..."
4,Kota Factory,TV Show,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...
8802,Zodiac,Movie,"Cult Movies, Dramas, ThrillersA political cart..."
8803,Zombie Dumb,TV Show,"Kids' TV, Korean TV Shows, TV ComediesWhile li..."
8804,Zombieland,Movie,"Comedies, Horror MoviesLooking to survive in a..."
8805,Zoom,Movie,"Children & Family Movies, ComediesDragged from..."
8806,Zubaan,Movie,"Dramas, International Movies, Music & Musicals..."

## Content-Based Filtering

In [ ]:
# import Tfidfvectorizer for creating vector matrix

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words = 'english')

tfidf_matrix = tfidf.fit_transform(new_df['tags'])

In [ ]:
tfidf_matrix.shape

(8807, 21387)

In [ ]:
from sklearn.metrics.pairwise import linear_kernel

cos_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [ ]:
# construct a reverse map of indices and movies title
indices =pd.Series(new_df.index, index = new_df['title']).drop_duplicates()

In [ ]:
indices

title
Dick Johnson Is Dead        0
Blood & Water               1
Ganglands                   2
Jailbirds New Orleans       3
Kota Factory                4
                         ...
Zodiac                   8802
Zombie Dumb              8803
Zombieland               8804
Zoom                     8805
Zubaan                   8806
Length: 8807, dtype: int64

In [ ]:
def get_recommendation(title, cos_sim = cos_sim):

  indx = indices[title]

  sim_scores = list(enumerate(cos_sim[indx]))

  sort_indices = sorted(sim_scores, key = lambda x: x[1], reverse = True)

  sim_scores = sort_indices[1:11]

  movie_indices = [int(i[0]) for i in sim_scores]

  return new_df.iloc[movie_indices]['title']

In [ ]:
get_recommendation('Ganglands')

3976               The Eagle of El-Se'eed
5305                               Narcos
3552                      The Good Bandit
7463                        Miss Dynamite
1349     Pablo Escobar, el patrón del mal
4750                             El Chapo
6652                   Dueños del paraíso
6741                        Fatal Destiny
424     Chhota Bheem: The Rise of Kirmada
5348     Close Your Eyes Before It’s Dark
Name: title, dtype: object

In [ ]:
get_recommendation('Zodiac')

5952         Victim of Beauty
4453    No One Killed Jessica
3065                  Messiah
1055                Zoot Suit
6007              3 Deewarein
6379        Brooklyn's Finest
200           Krishna Cottage
6212              Bad Boys II
1678         Raman Raghav 2.0
2220     Ip Man 4: The Finale
Name: title, dtype: object

In [ ]:
get_recommendation('Zombie Dumb')

2971               Diablero
4809          Kiss Me First
3071             Reply 1988
3358     Bring It On, Ghost
517       Good Morning Call
521       Kim's Convenience
3467                Inmates
5119    Hello, My Twenties!
7286                 Legion
1948            Van Helsing
Name: title, dtype: object